// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskBlaster.Data;

#nullable disable

namespace TaskBlaster.Migrations
{
    [DbContext(typeof(TaskBlasterDbContext))]
    [Migration("20250531150027_AddedUserSeed")]
    partial class AddedUserSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DutyResource", b =>
                {
                    b.Property<int>("DutiesId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourcesId")
                        .HasColumnType("integer");

                    b.HasKey("DutiesId", "ResourcesId");

                    b.HasIndex("ResourcesId");

                    b.ToTable("DutyResource");
                });

            modelBuilder.Entity("TaskBlaster.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Uid");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Work",
                            Uid = "a"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Home",
                            Uid = "a"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Personal Goals",
                            Uid = "a"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Errands",
                            Uid = "a"
                        });
                });

            modelBuilder.Entity("TaskBlaster.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int?>("DutyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DutyId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Waiting on data from finance team.",
                            DutyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Don't forget to recycle old paint cans.",
                            DutyId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Completed it in 28 minutes!",
                            DutyId = 3
                        });
                });

            modelBuilder.Entity("TaskBlaster.Models.Duty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Duties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Gather all department data and submit the final report to the manager.",
                            IsCompleted = false,
                            Priority = "High",
                            Title = "Submit monthly report"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Organize tools and dispose of unwanted items.",
                            IsCompleted = false,
                            Priority = "Medium",
                            Title = "Clean the garage"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Jog around the neighborhood for cardio.",
                            IsCompleted = true,
                            Priority = "Low",
                            Title = "Run 5K"
                        });
                });

            modelBuilder.Entity("TaskBlaster.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Vacuum Cleaner"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Notebook"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Car"
                        });
                });

            modelBuilder.Entity("TaskBlaster.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Uid = "a"
                        },
                        new
                        {
                            Id = 2,
                            Uid = "b"
                        });
                });

            modelBuilder.Entity("DutyResource", b =>
                {
                    b.HasOne("TaskBlaster.Models.Duty", null)
                        .WithMany()
                        .HasForeignKey("DutiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskBlaster.Models.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskBlaster.Models.Category", b =>
                {
                    b.HasOne("TaskBlaster.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("Uid")
                        .HasPrincipalKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskBlaster.Models.Comment", b =>
                {
                    b.HasOne("TaskBlaster.Models.Duty", "Duty")
                        .WithMany("Comments")
                        .HasForeignKey("DutyId");

                    b.Navigation("Duty");
                });

            modelBuilder.Entity("TaskBlaster.Models.Duty", b =>
                {
                    b.HasOne("TaskBlaster.Models.Category", "Category")
                        .WithMany("Duties")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TaskBlaster.Models.Category", b =>
                {
                    b.Navigation("Duties");
                });

            modelBuilder.Entity("TaskBlaster.Models.Duty", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TaskBlaster.Models.User", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
